//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Onep.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public int id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string CIN { get; set; }
        public Nullable<int> Tel { get; set; }
        public string Email { get; set; }
        public Nullable<int> Service_Id { get; set; }
        public string Fonction { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role_Id { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual service service { get; set; }
        public virtual agent agent1 { get; set; }
        public virtual agent agent2 { get; set; }
        public virtual agent agent11 { get; set; }
        public virtual agent agent3 { get; set; }
    }
}
