//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Onep.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int id { get; set; }
        public Nullable<int> id_agent { get; set; }
        public Nullable<System.DateTime> date_demande { get; set; }
        public Nullable<System.DateTime> du { get; set; }
        public Nullable<System.DateTime> au { get; set; }
        public Nullable<int> nbrjour { get; set; }
        public string type { get; set; }
        public string Precisions { get; set; }
        public string remark { get; set; }
        public Nullable<byte> opinion { get; set; }
    }
}
