//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Onep.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_agentEntities1 : DbContext
    {
        public gestion_agentEntities1()
            : base("name=gestion_agentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<agent> agent { get; set; }
        public DbSet<Demande> Demande { get; set; }
        public DbSet<registration> registration { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<service> service { get; set; }
        public DbSet<typeconge> typeconge { get; set; }
    }
}
