//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Onep.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public string UserName { get; set; }
        public string Passworde { get; set; }
        public string confirmPass { get; set; }
        public Nullable<int> mobile { get; set; }
        public string Adresse { get; set; }
    }
}
